\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{swsthesis}[2024/04/20 (C) by Stefan Mühlbauer]

\LoadClass[
	oneside,
	12pt,
]{book}

\RequirePackage{graphicx}
\RequirePackage{xcolor}
\RequirePackage{blindtext}
\RequirePackage[english]{babel}

% load font setup
\usepackage{sty/fonts}
\usepackage{sty/theme}
\usepackage{sty/macros}
\usepackage{sty/titleformat}
\usepackage{sty/titlepage}
\usepackage{sty/layout}
\usepackage{sty/lists}
\usepackage{sty/tocformat}
\usepackage{sty/typography}
\usepackage{sty/tables}
\usepackage{sty/hyper}
\usepackage{sty/headerfooter}
\usepackage{sty/bibliography}
\usepackage{sty/headerfooter}